### PR TITLE
Added #112 sign with cosignatories

### PR DESCRIPTION
**Pull request by rg911**
Issue: #112 

Added a few methods to cope with off chain aggregated complete transaction co signing. 

Please refer to [this scenario](https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/112#issuecomment-481291208) currently been discussed. 

**Problem found from discussion:**
1. Alice needs to create - sign - recreate - sign again
2. `CosignatureTransaction` cannot be created before aggregated transaction's been announced.
3. `signTransactionWithCosignatories(initiatorAccount: Account, cosignatories: Account[])` requires both initiator and the cosigners's account details, which makes it impossible to sign off chain.

**Solution proposed in this PR:**
 01. Alice creates the aggregated tx and serialize it, and generate the hash. Then send to Bob & Carol
      * Use the newly exposed `transaction.serialize()` methods to create transaction payload (without an initial signing). This method will create binary payload with signer and signatures showing as `0000000.....0000`
      * `transaction payload` can then be send to Bob & Carol off the chain.

02. Bob & Carol validate the transaction and cosigns the tx and sends it back to Alice
      * Created a new method `CosignatureTransaction.signTransactionPayload(account, transactionPayload)` which can sign the transaction with its payload. 
      * It will return object `CosignatureSignedTransaction` with signatures Alice expected.

      ```
      const signedTxBob = CosignatureTransaction.signTransactionPayload(accountBob, txPayloadHex);
      const signedTxCarol = CosignatureTransaction.signTransactionPayload(accountCarol, txPayloadHex);
      ```

03. Alice collects the cosignatures, recreate, sign, and announces the transaction
      * Alice will collect those signatures. 

      ``` 
      const cosignatureSignedTransactions = [
            new CosignatureSignedTransaction(signedTxBob.parentHash, signedTxBob.signature, signedTxBob.signer),
            new CosignatureSignedTransaction(signedTxCarol.parentHash, signedTxCarol.signature, signedTxCarol.signer),
        ]; 
      ```

      * Alice then recreate the ACT from payload
      ```
      const recreatedTx = TransactionMapping.createFromPayload(aggregateTransactionPayload) as AggregateTransaction;
      ```

      * To sign the transaction, Alice now use the new method which does not require both initiator Account and cosigners accounts.
      ```
      aggregatedTx.signTransactionGivenSignatures(accountAlice, cosignatureSignedTransactions);
      ```

### CODE REVIEW

**Comment by jontey** [comment]
Passing just the hash around is dangerous, as Bob and Carol will not know what they are signing. 

I would suggest that `CosignatureTransaction.signTransactionHashWith` receive a transaction payload rather than just the hash to force developers to pass the entire transaction rather than just the hash (even though the function doesn't do any checks).

The reason behind this is that if the function accepts a hash, most developers will just pass around the hash, making applications that are vulnerable (signing compromised transactions). By forcing the transaction payload, it will notify the developers to think, Hey, maybe I need to get the other side to check if the transaction I'm signing is correct; or make it easier for developers to implement the check (on Bob and Carol's side).

**Comment by rg911** [comment]
> Passing just the hash around is dangerous, as Bob and Carol will not know what they are signing.
> 
> I would suggest that `CosignatureTransaction.signTransactionHashWith` receive a transaction payload rather than just the hash to force developers to pass the entire transaction rather than just the hash (even though the function doesn't do any checks).
> 
> The reason behind this is that if the function accepts a hash, most developers will just pass around the hash, making applications that are vulnerable (signing compromised transactions). By forcing the transaction payload, it will notify the developers to think, Hey, maybe I need to get the other side to check if the transaction I'm signing is correct; or make it easier for developers to implement the check (on Bob and Carol's side).

Fair point, cheers @jontey 👍

**Comment by evias** [comment]
tests failing due to needed library update

**Comment by evias** [comment]
can you rebase @rg911 please ?

**Comment by rg911** [comment]
> can you rebase @rg911 please ?

done

**Pull request merged**
